### ISSUE TITLE
mariadb::statement::set_enum(unsigned int, char const*) is undefined

### ISSUE THREAD

**Issue by nunojpg** [viaduck/mariadbpp#24]

**Comment by kleest** [comment]
Good catch.  

According to the [client libary C documentation](https://dev.mysql.com/doc/refman/8.0/en/c-api-prepared-statement-type-codes.html), `ENUM` is not supported in statements. It results in the runtime error `Buffer type is not supported` (libmariadbclient 10.3.15).  
Although the MariaDB C Connector documentation [says otherwise](https://mariadb.com/kb/en/library/mysql_bind/), it is not working there as well (version 3.0.9).  
  
@roussosalex I suggest removing the setter. What do you think?

**Comment by roussosalex** [comment]
The setter was removed. Please use `set_unsigned32` or `set_string` instead, depending on your enum type.
